language: java

script: "./gradlew dist"

before_install:
  - lib/update-lib.sh

install:
  - echo sonatypeUsername=none >> gradle.properties
  - echo sonatypePassword=none >> gradle.properties

after_script:
  - rm -rf lib

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: YJpfHcHwjvKITZur9WQgiZbICxYbf499AHuDUBRjzoGLXFXBQV3spnILI5tQ2E/laL8RnZs/byYdNdOGLMIjY4Oyoq3/iE63RhZTXuP3P9lK8CqIqnHIYMZAc/jby+QG1AuSI1MlhAI5Q22myrXni9RyC3jNgQ4XiChXh+rpdYE=
  file: build/distributions/xmlcalabash1-deltaxml-$TRAVIS_TAG.zip
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
