language: java
script: gradle dist
install:
- echo sonatypeUsername=none >> gradle.properties
- echo sonatypePassword=none >> gradle.properties
deploy:
  provider: releases
  api_key:
    secure: CeHSwi5T/PY6+ORQocVlrBbY7c4YnPTqwwCrGMQjrS+1ZN5NyNuBebfu9yrVMToctA611vSziNr3y6jGl5ZZfpuDJjYGe9iDK4o6sv9KjUyPS6NACVJVq8h/Qf45eOnjSTwrKN3swBeQVWNtSYAfiJgZyLL7ZOJaXMHJELNISLA=
  file:
    - build/distributions/xmlcalabash1-deltaxml-$TRAVIS_TAG.zip
  on:
    tags: true
    all_branches: true
